#!/bin/bash
export APPDIR="$(dirname "$(readlink -f "$0")")"
export PATH="$APPDIR/usr/bin/:$PATH"
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$PATH"
export XDG_DATA_DIRS="$APPDIR/usr/share/:/usr/share/:$XDG_DATA_DIRS"

if ! command -v python3 &> /dev/null
then
    python3 $APPDIR/usr/bin/bottles
else
    python $APPDIR/usr/bin/bottles
fi
