name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Do not open issues for Windows executables not working in Bottles, if not installed through our installers. Bottles is a Wine prefix manager. If a Windows application doesn't work, it could be a Wine problem or a misconfiguration of the Wine prefix. Please visit [WineHQ](https://www.winehq.org) and [ProtonDB](https://www.protondb.com) for more information on the software you are trying to run. For additional support, use the [Programs](https://github.com/bottlesdevs/programs) repository.
        ⚠️ Do not open issues for bugs outside of [Bottles on Flathub](https://flathub.org/apps/details/com.usebottles.bottles), as we do not support packages from third-party repositories. If you can reproduce the bug(s) using Bottles on Flathub, then we will provide support, otherwise we will close the issue.
        
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## System information

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: |
        How did you install Bottles?

        If you use Bottles from your distribution package manager, please install [Bottles from Flathub](https://flathub.org/apps/details/com.usebottles.bottles) and try to reproduce the bug there. You might/will not get help if you don't run Bottles from Flathub.
      options:
        - Flatpak from Flathub
        - Flatpak from Flathub Beta
        - Flatpak from GitHub Artifacts
    validations:
      required: true

  - type: input
    id: distro
    attributes:
      label: Distribution
      description: In which Linux distribution did you encounter the bug?
      placeholder: Fedora 35, Arch Linux, Ubuntu 21.10..
    validations:
      required: true

  - type: textarea
    id: health-check
    attributes:
      label: Debugging Information
      description: |
        In Bottles, press the hamburger menu (`☰`) at the top right. Then press "About Bottles". Select "Troubleshooting", then "Debugging Information". Lastly, copy text and paste here.

        If you are unable to run Bottles, then you can retrieve information by running `flatpak run --command=bottles-cli com.usebottles.bottles info health-check` in the terminal.
      render: shell
      placeholder: |
        Display:
            X.org: true
            X.org (port): :99.0
            Wayland: false
        Graphics:
            vendors:
                nvidia:
                    vendor: nvidia
                    envs:
                        __NV_PRIME_RENDER_OFFLOAD: '1'
                        __GLX_VENDOR_LIBRARY_NAME: nvidia
                        __VK_LAYER_NV_optimus: NVIDIA_only
                    icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
                amd:
                    vendor: amd
                    envs:
                        DRI_PRIME: '1'
                    icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
            prime:
                integrated: *id001
                discrete: *id002
        Kernel:
            Type: Linux
            Version: 5.16.9-200.fc35.x86_64
        Distro:
            Name: GNOME
            Version: '"41 (Flatpak runtime)"'
        Tools:
            cabextract: true
            p7zip: true
            patool: true
            glibc_min: '2.33'
        Bottles_envs: null
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Troubleshooting Logs
      description: If applicable, run `flatpak run com.usebottles.bottles`, reproduce the issue and paste the logs here.
      render: shell
      placeholder: |
        [Errno 2] No such file or directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Opera-GX__185/bottle.yml'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
            result = self.task_func(*args, **kwargs)

          File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 194, in get_manager
            mng = Manager(window=window, repo_fn_update=repo_fn_update)

          File "/app/share/bottles/bottles/backend/managers/manager.py", line 135, in __init__
            times.update(self.checks(install_latest=False, first_run=True).data)

          File "/app/share/bottles/bottles/backend/managers/manager.py", line 189, in checks
            self.check_bottles()

          File "/app/share/bottles/bottles/backend/managers/manager.py", line 804, in check_bottles
            process_bottle(b)

          File "/app/share/bottles/bottles/backend/managers/manager.py", line 758, in process_bottle
            self.update_config(

          File "/app/share/bottles/bottles/backend/managers/manager.py", line 874, in update_config
            with open(os.path.join(bottle_path, "bottle.yml"), "w") as conf_file

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
