name: Feature Request
description: Suggest an idea for this project
title: "[Request]: "
labels: ["Feature request"]
assignees:
  - mirkobrombin
body:
  - type: markdown
    attributes:
      value: |
        ### Read here first
        Please try to respect the layout, be as concise as possible and link some resources if they can be useful to us to better understand the request. Maintain a friendly tone.
        !!! PLEASE DON'T OPEN ISSUES FOR PROGRAMS NOT RUNNING IN BOTTLES, USE THE programs REPOSITORY INSTEAD !!!
        
  - type: textarea
    id: what-happened
    attributes:
      label: Tell us the problem or your need
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: your-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: To fix this, I would [...]
    validations:
      required: true

  - type: textarea
    id: other-solutions
    attributes:
      label: Other solutions?
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context and references
      description: Add any other context or reference about the feature request here.
    validations:
      required: false
