on:
  push:
    branches: [main]
  pull_request:
name: Build Flatpak
jobs:
  flatpak:
    name: "build-packages"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/theevilskeleton/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: theevilskeleton/flatpak-github-actions/flatpak-builder@a84376c54ee2ef1e309bf2eb319037be8288e9e4
      with:
        bundle: bottles.flatpak
        manifest-path: build-aux/com.usebottles.bottles.Devel.json
        cache-key: flatpak-builder-${{ github.sha }}
