name: "build-deb"
on:
  push:
    branches:
      - 'v1'
jobs:
  build:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: "actions/checkout@v2"
      
      - name: Install prerequisite packages
        run: |
          sudo apt-get install fakeroot dh-virtualenv debhelper
          
      - name: build deb package
        run: |
          dpkg-buildpackage -rfakeroot -b -uc -us -d
          ls
          mv ../*.deb bottles.${{ github.sha }}.deb
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous-v1"
          prerelease: true
          title: "bottles v1 build ${{ github.sha }}"
          files: "bottles.${{ github.sha }}.deb"
