on:
  push:
    branches: [main]
  pull_request:
name: Pytest
jobs:
  pytest-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Ubuntu dependencies
      run: |
        sudo apt update
        sudo apt install -y libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
        sudo apt install -y libcurl4-openssl-dev libssl-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements.dev.txt
    - name: Test with pytest
      run: |
        python -m pytest --version
        python -m pytest bottles
